### ISSUE TITLE
Update autogen directory for compatibility with latest firefox (122.0)

### ISSUE THREAD

**Issue by pipelight** [dwarfmaster/arkenfox-nixos#44]
I stumbled upon this warning: Arkenfox version 119.0 does not match Firefox's (122.0)
I think i has sometyhing to do with what is inside the autogen directory.

**Comment by pipelight** [comment]
Okay i figured it out!

I generated the missing json with.

```sh
nix shell
cd autogen
perl ../generator/generator.pl
```

**Comment by dwarfmaster** [comment]
Should be fixed with the latest merge. Usually it takes a few days for the upstream to update an user.js on a new firefox version, then at the end of the week I have a github action that creates a pull request with the new version. And then I usually take a few days to notice it and merge it, so around a week of delay should be expected after each new firefox version.
